name: Flutter Web Build & EdgeOne Deploy
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable 
          flutter-version: '3.32.6'  

      - name: Install Dependencies
        run: flutter pub get

      - name: Set Permission
        run: chmod +x build.sh

      - name: Build Web Release
        run: ./build.sh --no-web-resources-cdn
        env:
          NODE_OPTIONS: '--max_old_space_size=8192'

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          accountId: '0afe5bc844ebf46ebb51a537d28bbb41'
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          directory: 'build/web'
          projectName: 'ricehome'


      - name: Deploy to EdgeOne Pages
        run: npx edgeone pages deploy build/web -n ricehome -t ${{ secrets.EDGEONE_API_TOKEN }}
        env:
          EDGEONE_API_TOKEN: ${{ secrets.EDGEONE_API_TOKEN }}
